PROGRAM MAIN
IMPLICIT NONE
INTEGER ::  i,  nts, inc, argl, stat, cur_int, lines, nprt, j, iprt, k
REAL(KIND=8), ALLOCATABLE ::  Gtmp(:,:,:,:)
CHARACTER(128) :: path, cur_file, incchar
LOGICAL :: exist_file = .true.
! This takes the txt files generated by mupfes and puts
! them into a binary file that can be used here

print *, "Reading args"

! Input path (including file name) and increment
CALL get_command_argument(number=1, length=argl)
! ALLOCATE(character(argl) :: path)
CALL get_command_argument(number=1, value=path, status=stat)

CALL get_command_argument(number=1, length=argl)
! ALLOCATE(character(argl) :: incchar)
CALL get_command_argument(number=2, value=incchar, status=stat)
READ(incchar,*,iostat=stat) inc

print *, "Looping over txt files to get lengths"
cur_int = 1
! Loop over files 1: to get size of matrix for Gtmps
DO WHILE(exist_file)
!   Construct current txt file
    WRITE(cur_file, *) cur_int
    cur_file = TRIM(ADJUSTL(path))//TRIM(ADJUSTL(cur_file))//'.txt'
    INQUIRE(FILE=cur_file, EXIST=exist_file)

!   First file: find number of particles to put into Gtmp & allocate
    IF(cur_int .eq. 1) THEN
        lines = 0
        OPEN(1,file = cur_file)
        DO
            READ(1,*,END=10)
            lines = lines + 1
        ENDDO
        10 CLOSE (1)
        nprt = lines/4
        lines = 0
    ENDIF
    lines = lines + 1
    cur_int = cur_int + inc
ENDDO
nts = lines - 1
ALLOCATE(Gtmp(nts,3,3,nprt))

print *, "Looping over and reading txt files"
! Now do the loop again, but read the files 1 by
cur_int = 1
DO i = 1, nts
!   Construct current txt file
    WRITE(cur_file, *) cur_int
    cur_file = TRIM(ADJUSTL(path))//TRIM(ADJUSTL(cur_file))//'.txt'
    
!   Open and read through it prt by prt
    OPEN(1,file = cur_file)
    DO j = 1, nprt
!       Skip identifier (will need to be changed for parallel)
        READ(1, *) iprt
!       Each line read gives three values
        DO k = 1,3
            READ(1, *) Gtmp(i,:,k, j)
        ENDDO
    ENDDO
    CLOSE(1)
    cur_int = cur_int + inc
ENDDO

print *, "Writing binary file"
! Binary write
OPEN(1,FILE = 'VG2.bin', ACCESS = 'stream', ACTION = 'write', FORM="unformatted")
WRITE(1) nts, nprt
WRITE(1) Gtmp(1:nts,:,:,1:nprt)

END PROGRAM MAIN