PROGRAM MAIN
IMPLICIT NONE
INTEGER ::  i,  nts, inc, argl, stat, cur_int, lines, nprt, j, iprt, k, procs
INTEGER :: start, cnt, maxid
INTEGER, ALLOCATABLE :: ids(:,:), idtmp(:)
REAL(KIND=8), ALLOCATABLE ::  Gtmp(:,:,:,:)
REAL(KIND=8) :: tmpall(3)
CHARACTER(128) :: path, cur_file, incchar
LOGICAL :: exist_file = .true.
! This takes the txt files generated by mupfes and puts
! them into a binary file that can be used here

print *, "Reading args"

cnt = COMMAND_ARGUMENT_COUNT()
IF(cnt .ne. 3) THEN
    print *, "ERROR: 3 arguments are needed, in the following order"
    print *, "Path to (including the name of) velocity gradient files"
    print *, "Increment velocity gradient files are saved in"
    print *, "Numbert of first velocity gradient file"
    stop
ENDIF

! Input path (including file name), increment, and starting file
CALL get_command_argument(number=1, length=argl)
! ALLOCATE(character(argl) :: path)
CALL get_command_argument(number=1, value=path, status=stat)

CALL get_command_argument(number=1, length=argl)
! ALLOCATE(character(argl) :: incchar)
CALL get_command_argument(number=2, value=incchar, status=stat)
READ(incchar,*,iostat=stat) inc

CALL get_command_argument(number=1, length=argl)
! ALLOCATE(character(argl) :: incchar)
CALL get_command_argument(number=3, value=incchar, status=stat)
READ(incchar,*,iostat=stat) start

print *, "Looping over txt files to get lengths"
cur_int = start
procs = 0
maxid = 0
ALLOCATE(idtmp(2))

! Loop over files 1: to get size of matrix for Gtmps
DO WHILE(exist_file)

!   Construct current txt file
    WRITE(cur_file, *) cur_int
    cur_file = TRIM(ADJUSTL(path))//TRIM(ADJUSTL(cur_file))//'.txt'
    INQUIRE(FILE=cur_file, EXIST=exist_file)

!   First file: find number of particles to put into Gtmp & allocate
    IF(cur_int .eq. start) THEN
        lines = 0
        OPEN(1,file = cur_file)
        DO

!           Need to know number of procs
            IF(MOD(LINES,4).eq.0) THEN
                READ(1,*,END=10) idtmp
                procs = MAX(procs,idtmp(2))
                maxid = MAX(maxid,idtmp(1))
            ELSE
                READ(1,*,END=10)
            ENDIF
            lines = lines + 1
        ENDDO
        10 CLOSE (1)

        nprt = lines/4
        lines = 0
    ENDIF

    lines = lines + 1
    cur_int = cur_int + inc
ENDDO
procs = procs + 1
nts = lines - 1
ALLOCATE(Gtmp(nts,3,3,nprt), ids(maxid,procs))
Gtmp(:,:,:,:) = 0D0

print *, "Looping over and reading txt files"

! Now do the loop again, but read the files 1 by
cur_int = start

DO i = 1, nts

!   Construct current txt file
    WRITE(cur_file, *) cur_int
    cur_file = TRIM(ADJUSTL(path))//TRIM(ADJUSTL(cur_file))//'.txt'
    
!   Open and read through it prt by prt
    OPEN(1,file = cur_file)
    j = 0
    lines = 0
    DO
        j = j+1

!       Read particle id
        READ(1, *, END=20) idtmp
        lines = lines+1

!       If it's the first time through, we need to give each particle
!       id from mupfes a numerical value
        IF(i.eq.1) THEN
            ids(idtmp(1), idtmp(2)+1) = j
        ENDIF

!       Get the index associated with this particle
        iprt = ids(idtmp(1), idtmp(2)+1)

!       Each line read gives three values
        DO k = 1,3
            lines = lines+1
            ! print *, i,k,iprt, lines, idtmp
            READ(1, *) tmpall
            Gtmp(i,:,k, iprt) = tmpall
        ENDDO
    ENDDO
    20 CLOSE(1)
    cur_int = cur_int + inc
ENDDO

print *, "Writing binary file"
! Binary write
OPEN(1,FILE = 'VG2.bin', ACCESS = 'stream', ACTION = 'write', FORM="unformatted")
WRITE(1) nts, nprt
WRITE(1) Gtmp(1:nts,:,:,1:nprt)

END PROGRAM MAIN